spring:
  application:
    name: student-management-api
  devtools:
    restart:
      enabled: true
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:./data/DB;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: student-management-api
    password: student-management-api
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: true
  h2:
    console:
      enabled: true