spring.application.name=student-management-api
# Configuração do banco de dados
spring.datasource.url=jdbc:h2:file:./data/DB;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=student-management-api
spring.datasource.password=student-management-api
spring.h2.console.enabled=true
# Configuração do JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.devtools.restart.enabled=true
